#:schema node_modules/wrangler/config-schema.json
name = "party-shopping-list-server"
main = "index.ts"
compatibility_date = "2024-10-11"
route = { pattern = "party-shopping-list.tinybase.cloud", custom_domain = true }

[[durable_objects.bindings]]
name = "PartyDurableObjects"
class_name = "PartyDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["PartyDurableObject"]
